apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-sa
  namespace: wiz
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webapp-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: webapp-sa
    namespace: wiz
